name: Build WiX Setup

on: [workflow_dispatch]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - name: Check out latest
      uses: actions/checkout@v1
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: '3.1.x'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup and add nuget to PATH
      uses: nuget/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore -SolutionDirectory $Env:GITHUB_WORKSPACE
#    - name: Restore NuGet packages (ProjectSetup)
#      run: msbuild $Env:GITHUB_WORKSPACE\setup\ProjectSetup.wixproj /t:RestorePackages
    - name: Build with msbuild
      run: msbuild $Env:GITHUB_WORKSPACE\setup\ProjectSetup.wixproj -p:Configuration=Release -p:Platform=x86 -p:SolutionDir=$Env:GITHUB_WORKSPACE\
    - name: Archive setup build artifact
      uses: actions/upload-artifact@v2
      with:
        name: project-setup
        path: bin/*.msi
