name: Import certificate

on: 
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Create certificate with OpenSSL
        run: |
          echo "${{secrets.YV_CODESIGN_CERT}}" > codesign.crt
          echo "${{secrets.YV_CODESIGN_PKEY}}" > codesign.key
          openssl pkcs12 -export -out codesign.pfx -inkey codesign.key -in codesign.crt -passin pass:${{secrets.YV_CODESIGN_PKEY_PASS}} -passout pass:${{secrets.YV_CODESIGN_PFX_PASS}}
      - uses: actions/upload-artifact@v2
        with:
          name: certificate
          path: codesign.pfx
